# Generated by Django 3.0.7 on 2020-06-14 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experimentName', models.CharField(max_length=50, verbose_name='Experiment Name')),
                ('modeOp', models.CharField(max_length=50, verbose_name='Mode of Operation')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumentName', models.CharField(max_length=50, verbose_name='Instrument Name')),
                ('description', models.TextField(verbose_name='Description of the instrument')),
                ('instrumentType', models.CharField(max_length=50, verbose_name='Instrument Type')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristicName', models.CharField(max_length=50, verbose_name='Characteristic of a instrument')),
                ('characteristicsValue', models.CharField(max_length=50, verbose_name='Value of the Characteristic')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=50, verbose_name='Name of the model')),
                ('description', models.CharField(max_length=50, verbose_name='Description of the model')),
                ('modelType', models.CharField(max_length=50, verbose_name='Model Type')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationName', models.CharField(max_length=50, verbose_name='Station Name')),
                ('long', models.CharField(max_length=50, verbose_name='Longitude')),
                ('lat', models.CharField(max_length=50, verbose_name='Latitude')),
                ('description', models.CharField(max_length=50, verbose_name='Description of the station')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settingsName', models.CharField(max_length=50, verbose_name='Settings Name')),
                ('settingValue', models.CharField(max_length=50, verbose_name='Setting Value')),
                ('experimentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Experiment', verbose_name='Experiment Name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50, verbose_name='Product Name')),
                ('filePath', models.CharField(max_length=50, verbose_name='File Path')),
                ('productType', models.CharField(max_length=50, verbose_name='Tipo de producto')),
                ('experimentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Experiment', verbose_name='')),
                ('instrumentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Instrument', verbose_name='Instrument Name')),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='stationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Station', verbose_name='Station Name'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='instrumentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Instrument', verbose_name=''),
        ),
    ]
