# Generated by Django 3.0.7 on 2020-06-18 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='instrumentImage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='data/instruments', verbose_name='Instrument Image'),
            preserve_default=False,
        ),
    ]
